apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rust-app
  name: rust-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rust-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rust-app
    spec:
      containers:
        - image: "teewasza8989/rust-workshop-jumpbox:v0.0.2"
          name: rust-workshop-jumpbox
          resources: {}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-env
status: {}
